//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteEscritorioSOAP.ServicioBancario {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioBancario.ServicioBancarioSoap")]
    public interface ServicioBancarioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Depositar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Depositar(string cuenta, decimal monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Depositar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DepositarAsync(string cuenta, decimal monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Retirar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Retirar(string cuenta, decimal monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Retirar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RetirarAsync(string cuenta, decimal monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Transferir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Transferir(string cuentaOrigen, string cuentaDestino, decimal monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Transferir", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TransferirAsync(string cuentaOrigen, string cuentaDestino, decimal monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarSaldo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        decimal ConsultarSaldo(string cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarSaldo", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> ConsultarSaldoAsync(string cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarMovimientos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultarMovimientos(string cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarMovimientos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ConsultarMovimientosAsync(string cuenta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioBancarioSoapChannel : ClienteEscritorioSOAP.ServicioBancario.ServicioBancarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioBancarioSoapClient : System.ServiceModel.ClientBase<ClienteEscritorioSOAP.ServicioBancario.ServicioBancarioSoap>, ClienteEscritorioSOAP.ServicioBancario.ServicioBancarioSoap {
        
        public ServicioBancarioSoapClient() {
        }
        
        public ServicioBancarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioBancarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioBancarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioBancarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Depositar(string cuenta, decimal monto) {
            return base.Channel.Depositar(cuenta, monto);
        }
        
        public System.Threading.Tasks.Task<string> DepositarAsync(string cuenta, decimal monto) {
            return base.Channel.DepositarAsync(cuenta, monto);
        }
        
        public string Retirar(string cuenta, decimal monto) {
            return base.Channel.Retirar(cuenta, monto);
        }
        
        public System.Threading.Tasks.Task<string> RetirarAsync(string cuenta, decimal monto) {
            return base.Channel.RetirarAsync(cuenta, monto);
        }
        
        public string Transferir(string cuentaOrigen, string cuentaDestino, decimal monto) {
            return base.Channel.Transferir(cuentaOrigen, cuentaDestino, monto);
        }
        
        public System.Threading.Tasks.Task<string> TransferirAsync(string cuentaOrigen, string cuentaDestino, decimal monto) {
            return base.Channel.TransferirAsync(cuentaOrigen, cuentaDestino, monto);
        }
        
        public decimal ConsultarSaldo(string cuenta) {
            return base.Channel.ConsultarSaldo(cuenta);
        }
        
        public System.Threading.Tasks.Task<decimal> ConsultarSaldoAsync(string cuenta) {
            return base.Channel.ConsultarSaldoAsync(cuenta);
        }
        
        public System.Data.DataSet ConsultarMovimientos(string cuenta) {
            return base.Channel.ConsultarMovimientos(cuenta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ConsultarMovimientosAsync(string cuenta) {
            return base.Channel.ConsultarMovimientosAsync(cuenta);
        }
    }
}
